packages:
  - sdk/forgeops-feedback-core
  - sdk/forgeops-feedback-dom
  - sdk/forgeops-feedback-vue
  - sdk/forgeops-feedback-vue2
  - sdk/forgeops-feedback-react
  - examples/demo-app/web
  - examples/demo-app/react-demo
  - examples/demo-app/vue2-demo
